## Try Except Blocks üõ°Ô∏è

Errors are bound to occur in your code every now and then. They can be due to numerous reasons such as mismatches in the data types, wrong file paths, network shortages, etc. Fortunately, Python offers a way to catch and handle these errors using the `Try` and `Except` blocks. 

The `Try` block lets you test a chunk of code for errors. The `Except` block lets you handle the error.

Here's a basic example:

```python
try:
    print(x)
except:
    print("An error occurred!")
```

In the above example, we haven't defined `x`. If we run this piece of code, the Python interpreter will reach the `Try` block, and then trying to print `x` will throw an error. Now instead of completely breaking the program, it will move to the `except` block, and print "An error occurred!".

You can specify different types of exceptions under multiple `Except` blocks. This means you can customize the handling of different exceptions in different ways. Check this out:

```python
try:
    print(x)
except NameError:
    print("Variable x is not defined")
except:
    print("Something else went wrong")
```
In this code, if the exception is a `NameError` (which it is, because `x` is undefined), the program will print "Variable x is not defined". For any other kind of error, it'll print "Something else went wrong".

Finally, `Try Except Blocks` can also have an `else` clause. The code inside `else` will run if no exceptions were raised:
```python
try:
    print("Hello")
except:
    print("Something went wrong")
else:
    print("Nothing went wrong")
```
Here, since the `Try` block won't raise any errors, the `else` block will run and print "Nothing went wrong".

By now, you should have a decent understanding of `Try Except Blocks` in Python üõ°Ô∏è. They are your shield against unexpected errors, providing you a controlled environment to handle them gracefully without breaking your program flow. Keep this shield polished, as it will protect your code numerous times along your journey! Happy coding! üíª